# Generated by Django 5.0.6 on 2024-07-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.TextField()),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')])),
            ],
        ),
        migrations.DeleteModel(
            name='Accountcreate',
        ),
    ]
